- name: CREATING SERVICE ACCOUNT ON THE SERVER.
  user:
    name: "{{ansible_svc}}"
    state: present
  register: service_account_creation
  ignore_errors: true
- debug: var=service_account_creation
