- name: CREATING SSH FOLDER IN THE HOME DIRECTORY OF GIVEN USER
  become_user: "{{ansible_svc}}"
  file:
    path: "/home/{{ansible_svc}}/.ssh"
    mode: "0700"
    owner: "{{ansible_svc}}"
    state: directory
- name: CREATING SSH KEY PAIR IN THE CONTROL NODE
  become_user: "{{ansible_svc}}"
  openssh_keypair:
    path: /home/{{ansible_svc}}/.ssh/id_rsa
    mode: '0600'
  register: key_pair_creation
- name: SETTING FACT FOR PUBLIC KEY
  set_fact: pub="{{key_pair_creation.public_key}}"
- name: SAVING THE PUBLIC KEY
  become_user: "{{ansible_svc}}"
  copy:
    content: "{{pub}}"
    dest: "/home/{{ansible_svc}}/.ssh/id_rsa.pub"
    mode: '0644'
  register: store_public_key
- name: DISABLE HOST_KEY CHECKING
  become_user: "{{ansible_svc}}"
  copy:
    src: config
    dest: "/home/{{ansible_svc}}/.ssh/config"
    mode: "0400"
    owner: "{{ansible_svc}}"
