---
- hosts: localhost
  tasks:
  - name: CREATING AN IN-MEMORY INVENTORY FOR CONTROL_NODE
    add_host:
       hostname: "{{control_node}}" # localhost
       groups: control_node
  - name: CREATING A COMMON IN-MEMORY INVENTORY
    add_host:
        hostname: "{{item}}"
        groups: common_group
    with_items:
        - "{{target_nodes}}"
        - "{{control_node}}"
  - name: CREATING AN IN-MEMORY INVENTORY FOR TARGET HOSTS
    add_host:
        hostname: "{{item}}"
        groups: target_host
    with_items:
     - "{{target_nodes}}"
- hosts: common_group  
  become: true
  tasks:
    - name: "CREATING SERVICE ACCOUNT - {{ansible_svc}} IN CONTROL AND TARGET SERVERS"
      include_role:
        name: passwordless_authentication
        tasks_from: create_service_account
    - name: "MAKE SUDOERS ENTRY OF CREATED USER - {{ansible_svc}}"
      include_role:
        name: passwordless_authentication
        tasks_from: make_sudoers_entry
- hosts: control_node
  become: true
  tasks:
    - name: CREATING SSH-KEYPAIR ON CONTROL_NODE
      include_role:
         name: passwordless_authentication
         tasks_from: passwordless_auth_operations
- hosts: target_host
  become: true
  tasks:
    - name: COPY THE AUTHORIZED KEY FROM CONTROL NODE TO TARGET SERVERS
      include_role:
        name: passwordless_authentication
        tasks_from: copy_authorized_keys
- hosts: all
  become: true
  tasks:
    - name: DISABLE TEMPORARY USER ON ALL NODES
      user:
        name: "{{ansible_user}}"
        expires: "{{ansible_date_time.epoch}}"
      async: 5
      poll: 0
      when: Disable_Temp_user == True
